# YAML
workingBranch:
  value: ""
commitAuthor:
  value: ""
workingDir:
  value: /var/www/
backupDir:
  value: ""
webrootDir:
  value: ""
blacklist:
  value: ""
deploymentTickets:
  value:
    - Staging
    - Production
upCmds:
  value:
    - -y
    - --security-only
    - --no-backup
drushAliasFile:
  value: drupdates.aliases.drushrc.php
datastoreDriver:
  value: mysql

