# YAML
workingBranch:
  value: ""
commitAuthor:
  value: ""
workingDir:
  value: /var/www/
backupDir:
  value: ""
blacklist:
  value: ""
upCmds:
  value:
    - -y
    - --security-only
    - --no-backup
